apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongo
  labels:
    app: shroomate
    component: mongo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: shroomate
      component: mongo
  serviceName: mongo
  template:
    metadata:
      labels:
        app: shroomate
        component: mongo
    spec:
      restartPolicy: Always
      containers:
      - image: mongo:7.0
        name: mongo
        livenessProbe:
          tcpSocket:
            port: mongo
          failureThreshold: 2
          periodSeconds: 11
        startupProbe:
          tcpSocket:
            port: mongo
          failureThreshold: 30
          periodSeconds: 11
        readinessProbe:
          exec:
            command:
              - mongosh
              - --eval
              - "db.adminCommand('ping')"
          timeoutSeconds: 5
          failureThreshold: 2
#        env:
#        - name: MONGODB_INITDB_ROOT_USERNAME
#          valueFrom:
#            secretKeyRef:
#              name: shroomate
#              key: db_username
#        - name: MONGODB_INITDB_ROOT_PASSWORD
#          valueFrom:
#            secretKeyRef:
#              name: shroomate
#              key: db_password
        ports:
        - containerPort: 27017
          name: mongo
        volumeMounts:
        - name: mongo-datadb
          mountPath: /data/db
      volumes:
      - name: mongo-datadb
        persistentVolumeClaim:
          claimName: mongo
