apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongo
  labels:
    app: shroomate
    component: mongo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: shroomate
      component: mongo
  serviceName: mongo
  template:
    metadata:
      labels:
        app: shroomate
        component: mongo
    spec:
      containers:
      - image: mongo:7.0
        name: mongo
        env:
        - name: MONGODB_INITDB_ROOT_USERNAME
          valueFrom:
            secretKeyRef:
              name: shroomate
              key: db_username
        - name: MONGODB_INITDB_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: shroomate
              key: db_password
        ports:
        - containerPort: 27017
          name: mongo
        volumeMounts:
        - name: mongo-data
          mountPath: /data/db
  volumeClaimTemplates:
  - metadata:
      name: mongo-data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 1Gi
