apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongo
  labels:
    app: shroomate
    component: mongo
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  name: mongo
